server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testapp
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non_null
  rabbitmq:
    exchange:
      name: javaguides_exchange
    routing:
      key: javaguides_routing_key
    name: myqueue
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG